#!/usr/bin/env bash

set -eo pipefail

OPTIONS=$(getopt -o "g:" --long "gem:" -- "$@")

if [ $? -ne 0 ]; then
  echo "Failed to parse options." >&2
  exit 1
fi

eval set -- "$OPTIONS"
GEM=""

while true; do
  case "$1" in
    -g|--gem)
      GEM=$2
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Invalid option specified: $1" >&2
      exit 1
      ;;
  esac
done

echo "Building gem: $GEM"
pushd "gems/$GEM" &>/dev/null
bundle install
bundle exec rake build
popd &>/dev/null
