#!/usr/bin/env bash

set -eo pipefail

while getopts "g:" opt; do
  case $opt in
    g) GEM="$OPTARG" ;;
  esac
done

shift $((OPTIND-1))

if [ -z "$GEM" ]; then
  echo "Error: gem to build not specified"
fi

echo "Building gem: $(basename $GEM)"
pushd "$GEM" &>/dev/null
bundle install
bundle exec rake build
popd &>/dev/null
