#!/usr/bin/env bash

set -eo pipefail

: "${GEM_HOST_API_KEY}"
: "${PUSH_HOST}"

OPTIONS=$(getopt -o "g:" --long "gem:" -- "$@")

if [ $? -ne 0 ]; then
  echo "Failed to parse options." >&2
  exit 1
fi

eval set -- "$OPTIONS"
GEM=""

while true; do
  case "$1" in
    -g|--gem)
      GEM=$2
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Invalid option specified: $1" >&2
      exit 1
      ;;
  esac
done

if [ ! -f $HOME/.gem/credentials ]; then
  mkdir -p $HOME/.gem
  touch $HOME/.gem/credentials
  chmod 0600 $HOME/.gem/credentials
  printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
fi

echo "Pushing gem: $GEM"
pushd "gems/$GEM" &>/dev/null
gem push --key github --host $PUSH_HOST pkg/*.gem
popd &>/dev/null
done
