#!/usr/bin/env bash

set -euo pipefail

: "${GEM_HOST_API_KEY}"
: "${PUSH_HOST}"

while getopts "g:" opt; do
  case $opt in
    g) GEM="$OPTARG" ;;
  esac
done

shift $((OPTIND-1))

if [ -z "$GEM" ]; then
  echo "Error: gem to build not specified"
fi

if [ ! -f $HOME/.gem/credentials ]; then
  mkdir -p $HOME/.gem
  touch $HOME/.gem/credentials
  chmod 0600 $HOME/.gem/credentials
  printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
fi

echo "Pushing gem: $(basename $GEM)"
pushd "$GEM" &>/dev/null
gem push --key github --host $PUSH_HOST pkg/*.gem
popd &>/dev/null
